name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
          web/target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Build main project
      run: cargo build --verbose
      
    - name: Build web project
      run: cargo build --verbose --manifest-path web/Cargo.toml
      
    - name: Run main project tests
      run: cargo test --verbose
      
    - name: Run web project tests
      run: cargo test --verbose --manifest-path web/Cargo.toml

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy
        
    - name: Run Clippy on main project
      run: cargo clippy --all-targets --all-features -- -D warnings
      
    - name: Run Clippy on web project
      run: cargo clippy --all-targets --all-features --manifest-path web/Cargo.toml -- -D warnings

  format:
    name: Format Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
        
    - name: Check main project formatting
      run: cargo fmt --all -- --check
      
    - name: Check web project formatting
      run: cargo fmt --all --manifest-path web/Cargo.toml -- --check

