name: Rust Format Check

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  format:
    name: Check Code Format
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
        
    - name: Check main project formatting
      run: cargo fmt --all -- --check
      
    - name: Check web project formatting
      run: cargo fmt --all --manifest-path web/Cargo.toml -- --check

